### PR TITLE
Added in support for autocompleting `enumerate`.

### LINKED ISSUE #554: Jedi doesn't understand `enumerate`
For example,
```python
colors = ['red', 'green', 'blue']
for color in colors:  
    print color.upper()
```
In this loop jedi correctly identifies that `color` is a `str`.

However, if I use enumerate:
```python
colors = ['red', 'green', 'blue']
for i, color in enumerate(colors):
    print i, '-->', color.upp#?
```
jedi has no idea what `color` is.

### PR DESCRIPTION
**Pull request by squidarth**
@davidhalter Resolves #554, Jedi now understands `enumerate`.

I took a similar approach to `reversed` and a few other stdlib functions.  Let me know what you think.  Just started poking around the jedi codebase this weekend, thought this was a good place to start contributing.

Thanks so much for building this awesome library!

### CODE REVIEW

**Comment by davidhalter** [comment]
Nice! Yeah this exactly how you should be doing it :-)

Can you please add yourself to `AUTHORS.txt`?

**Comment by squidarth** [comment]
Great, done.

**Comment by davidhalter** [comment]
Thanks so much @squidarth!

**Comment by davidhalter** [comment]
Oh and if you're interested, I'm very happy to give you more work :)

**Comment by squidarth** [comment]
Happy to--let me know the best place to discuss

**Comment by davidhalter** [comment]
At this point, fixing bugs is not the big work anymore. Most of them have been fixed or are very hard to if you don't know the codebase very well.

I'm just going to suggest a few different features:

- Refactoring #103
- Semantic keyword completion #580
- Supporting del #313 (small issue)
- Dynamic classes (with type) #516 

In order of importance :-)
The first two issues are quite a bit of work, but you don't need to finish it. All of those are things that I would really like to see done in Jedi, but don't really find time myself (I'm busy with the linter part, currently). 

If you're interested in one of them, let me know, just comment in one of these issues and I will give you an introduction. Some of those things are really hard to do if you don't know where to start, but easy if you know where to look :)

**Pull request merged**
