### PR TITLE
implemented .get() for MergedNamesDict, see #589

### PR DESCRIPTION
**Pull request by avkoval**
Made .get() and added test for this use-case for issue #589

### CODE REVIEW

**Comment by davidhalter** [comment]
But what's the actual problem? How and where does this occur? This is what I want to know first.

**Comment by davidhalter** [comment]
But thanks anyway for the implementation.

Sorry for not just merging. I have realized along the line that bugs like this one haunts you somewhere later in point. So I always want to know what exactly the issue is. It's so easy to hot-fix something in Python with try/except.

**Comment by RichardBronosky** [comment]
Thank you for this patch! Confirmed to fix https://github.com/davidhalter/jedi/issues/589#issuecomment-161541334 and https://github.com/davidhalter/jedi/issues/589#issuecomment-152909087 added to https://github.com/sadovnychyi/autocomplete-python/commit/b4e575b08cc8acce6fb640a6a3afc92bff78ab70

**Comment by mathieulongtin** [comment]
Will this get merged eventually? I get this error using YouCompleteMe's latest as of today.

**Comment by davidhalter** [comment]
No it will not. You could as well be doing:

   try:
       jedi.Script.completions
   except:
       pass

This pull request is not a fix, because it doesn't solve the problem. It might be the fix, but I want to know why this happens, first.

**Comment by mathieulongtin** [comment]
My stack trace is similar to issue #589. I'm not sure what causes it to happen in the first place, but it seems that a MergedNamesDict ends up in another MergedNamesDict. Since the `__getitem__` of that class uses `get`, probably assuming that it only has dict inside, it fails.

When I saw that stack trace, I added a `get` like this, so it would behave like a dict.
```
    def get(self, name, default=None):
        try:
            return self[name]
        except KeyError:
            return default
```
Not quite the same as for this patch, but anyway. My `jedihttp*stderr.log` have been empty since then, and I get much better name suggestions than before, because my jedi process doesn't die half the time.

**Comment by davidhalter** [comment]
> MergedNamesDict ends up in another MergedNamesDict

Yes, but I this shouldn't even happen. I think we have a bigger issue there.

**Comment by davidhalter** [comment]
I have fixed it in a branch.

What this issue showed me is that a lot of people try to solve stuff with try/except in Python instead of fixing the actual issue, which makes me a bit sad.

**Comment by avkoval** [comment]
Right, I've seen your comment (how to make correct fix) but it would take a lot of time for me to get into the whole picture/details. Thank you for applying correct fix here!

**Comment by davidhalter** [comment]
Well, it's not very much a critic of your approach here, I'm just seeing this again and again :)

**Pull request closed without merging**
