### PR TITLE
run buildout detection only once per buildout script

### PR DESCRIPTION
**Pull request by mfussenegger**
same as https://github.com/davidhalter/jedi/pull/546 but against the dev branch

### CODE REVIEW

**Comment by davidhalter** [comment]
Hmm why aren't you using the parser caches? I would probably prefer that to a memoize call, since that will cache the buildout scripts for future usages as well.

**Comment by mfussenegger** [comment]
Saw your updated comment only after I've already changed it to use the memoize call. 
If you want I can try to use the parser caches instead.

**Comment by davidhalter** [comment]
Yeah I guess I would prefer that, since it's not really clear why we need the memoize call there from just reading the code, it doesn't see like a very "slow" thing from the outside.

But nice fix anyways. It looks good.

**Comment by mfussenegger** [comment]
Added another fixup which now uses the parser cache. Let me know if it's okay, I'll then squash the commits.

**Comment by davidhalter** [comment]
Nice! I like it! I just realized that I screwed up the whole test suite a while ago. But I'll fix that and you can squash.

Thanks a lot.

**Comment by mfussenegger** [comment]
Rebased and squashed it.

**Comment by davidhalter** [comment]
Thanks so much for the effort :)

**Pull request merged**
