### PR TITLE
Improve virtualenv support & egg-link resolution

### LINKED ISSUE #443: .pth status
* pth in user or global site-packages seem to work OK. Therefore, as I can see, they are not covered by tests (and not obvious that they are actually required).
* pth inside virtualenv's site-packages is broken. And tests are required.
* #345 solution seems to be broken in two points. First, only pth files from site-packages dirs should be included, but in that solution pth files from all sys.path entries are included. Second, in original site.py code there is probably (didn't check, `makepath` func) a workaround for windows case-insensitive paths (?).
* I have some doubt about how it exactly should be implemented.
  * add pth parsing directly in sys.path? Looks hacky, but as soon as venv's site-packages is dealed in sam way, it should be ok.
  * I didn't investigate what is the correct place for these paths. Probably, after venv's site-packages dir.

Will fix it if have a time. Otherwise, hope my comments will help to fix it in future.

### PR DESCRIPTION
**Pull request by immerrr**
This PR implements the offline part of the functionality implemented in #562 so that it's easier to discuss and commit regardless of the decision about fetching path from live interpreter. It also extends venv-related tests a bit.

It should fix #443 and #384, also might help with #560 and #535.

### CODE REVIEW

**Comment by davidhalter** [comment]
Very awesome. Thanks a lot!! There are some tests failing (haven't looked into it).

**Comment by immerrr** [comment]
@davidhalter it seems that the test failure is an issue in pytest, it cannot find a fixture and falls apart trying to report it (reported as pytest-dev/pytest#1148). I worked it around by adding `testpaths = test` to `pytest.ini`, but it might be yet another issue with doctest fixture discovery.

**Comment by immerrr** [comment]
huh, travis caught an actual failure, let me look into it

**Comment by immerrr** [comment]
There's also a hack in emacs jedi epc server that refers to #36 and mentions caching issues. I have added a test to ensure that `sys_path=` kwarg plays well with caching, just in case.

**Comment by immerrr** [comment]
All green after rebasing on top of #637.

**Comment by davidhalter** [comment]
I like this pull request a lot. It's really fine work!!! :)

I'm not merging yet, for one minor reason. I think I have talked about #562 before:
I struggle a bit about just including it, because it allows (as far as I remember) execution of arbitrary Python code, which is not allowed in Jedi, yet. Is there no other option of doing it maybe in a different way (with Jedi introspection)? Which (well-known) packages does it benefit? Examples?

**Comment by immerrr** [comment]
I have done a quick grep through pth files on my system and all of the custom code in pth files is either easy_install bootstrap code:

```python
import sys; sys.__plen = len(sys.path)
./jeditestmodule-0.0.0-py2.7.egg
/home/immerrr/sources/jedi
/home/immerrr/sources/pytest
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)
```
or namespace package bootstrap code:
```python
import sys,types,os; p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('sphinxcontrib',)); ie = os.path.exists(os.path.join(p,'__init__.py')); m = not ie and sys.modules.setdefault('sphinxcontrib',types.ModuleType('sphinxcontrib')); mp = (m or []) and m.__dict__.setdefault('__path__',[]); (p not in mp) and mp.append(p)
```

I think those can be skipped without any harm to sys.path detection. What worries me is that `eval SMTH` in `site.addpackage` function cannot be disabled, so either mocking or copy-pasting it is required.

**Comment by davidhalter** [comment]
Since we're just adding to the `sys.path`, we can just add al the paths to it, ignore the `import` lines and that's it? Or would it be more complicated?

**Comment by immerrr** [comment]
standard library employs case-sensitivity hacks, so it seems better to just pull in some well-debugged code under a permissive license than to reimplement it from scratch.

**Comment by immerrr** [comment]
(which i have done)

**Comment by davidhalter** [comment]
Very, very nice! I like this PR a lot. Thanks so much!

It's a lot already, I'm really glad we didn't mix it with the VIRTUAL_ENV stuff anymore. Can you briefly describe in #562, what the leftovers are? What still would need to be done?

**Comment by immerrr** [comment]
There are several issues that are affected by this PR directly, #443 and #384 should be fixed now, #560 and #535 are a bit vague, but might be fixed too.

**Comment by davidhalter** [comment]
Wow that's a lot of fixes. :) Thanks a lot (for also searching all the issues).

**Pull request merged**
