### PR TITLE
Add API to find the virtual_env of single venv path

### PR DESCRIPTION
**Pull request by 15cm**
Extract a `find_virtualenv` function to find single venv with given path. This function provides the API for _pyenv_ support in _python-language-server_: [Support pyenv virtualenv for LSP project roots ](https://github.com/15cm/python-language-server/commit/e3433c891dbce8131de005a3b9e4dba586bc8a33)

### CODE REVIEW

**Comment by davidhalter** [comment]
Why not use `list(find_virtualenvs([path]))`?

I feel like if we want to publish your API we should stay consistent with `get_system_environment`, which raises `InvalidPythonEnvironment` if it doesn't work.

Do you really prefer the exception solution to the iterator?

**Comment by 15cm** [comment]
> Why not use `list(find_virtualenvs([path]))`?
> 
> I feel like if we want to publish your API we should stay consistent with `get_system_environment`, which raises `InvalidPythonEnvironment` if it doesn't work.
> 
> Do you really prefer the exception solution to the iterator?

Because `find_virtualenvs` finds venv in all directories under each path:
[paths] -> path -> [dirs] -> dir -> dir/bin/python
But I want a API that returns a venv for a given directory:
dir -> dir/bin/python

In fact I think it's more sensible for `find_virtualenvs` to do this:
[paths] -> path -> path/bin/python
But since this is not the case, I have to extract an API out of the function.

As for the exception, I just follow the logic of `find_virtualenvs`, where the exception is ignored.

**Comment by davidhalter** [comment]
Ok. I understand your point and I also agree that it's not obvious. Why are you then not using `create_environment`? It looks like that would work for you.

**Comment by 15cm** [comment]
That's exactly what I want, thank you. BTW I will appreciate if you can make the comment of `find_virtualenvs` clearer.

**Comment by davidhalter** [comment]
Feel free to suggest something better. I get that it is a problem, but I'm not the best writer :).

**Pull request closed without merging**
