### PR TITLE
subprocess: do not mute stderr

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/davidhalter/jedi/issues/1165.

### CODE REVIEW

**Comment by davidhalter** [comment]
Note that this won't change anything, because there's still `stderr=subprocess.PIPE`. IMO we should keep that, read what's in there (not sure how easily that will be possible) and log that.

**Comment by blueyed** [comment]
> there's still stderr=subprocess.PIPE

This allows to read it after all, i.e. I think it should be kept.
Are you sure that this PR will not change anything?

**Comment by davidhalter** [comment]
Well, this change will get capture stderr on the parent process side and you will not see anything.

**Comment by davidhalter** [comment]
As you can see it in the commit, I think I addressed your concerns here. Please tell me if there's still something wrong.

**Comment by blueyed** [comment]
Thanks, LGTM (although more complex, but I'm sure for reasons ;))

**Pull request closed without merging**
