### PR TITLE
Fix: check node before parso.python.tree.search_ancestor

### PR DESCRIPTION
**Pull request by m9810223**

### CODE REVIEW

**Comment by davidhalter** [comment]
What does this fix?

**Comment by m9810223** [comment]
> What does this fix?

hi @davidhalter, that fix `from fastapi import <tab>` error in `ipython`.

**Comment by davidhalter** [comment]
Could you post the traceback?

I'm not sure how used to writing automated tests you are. It would be ideal if you would add one, but if you do not, I at least need to understand why this change is necessary.

**Comment by m9810223** [comment]
```python
Traceback (most recent call last):
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/cache.py", line 110, in wrapper
    return dct[key]
KeyError: ((), frozenset({('resolve_stars', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deb1/.local/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 115, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/deb1/.local/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 131, in _get_completions
    for c in completions:
  File "/home/deb1/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 450, in _deduplicate_completions
    completions = list(completions)
  File "/home/deb1/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1843, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/deb1/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1900, in _completions
    signature = _make_signature(jm)
  File "/home/deb1/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1012, in _make_signature
    return '('+c0.to_string().split('(', maxsplit=1)[1]
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/api/classes.py", line 820, in to_string
    return self._signature.to_string()
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/signature.py", line 31, in to_string
    s = self.name.string_name + '(' + ', '.join(param_strings()) + ')'
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/signature.py", line 13, in param_strings
    for n in self.get_param_names(resolve_stars=True):
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/signature.py", line 97, in get_param_names
    params = process_params(params)
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/star_args.py", line 192, in process_params
    for p in process_params(
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/star_args.py", line 192, in process_params
    for p in process_params(
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/star_args.py", line 192, in process_params
    for p in process_params(
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/star_args.py", line 125, in process_params
    kwarg_callables = list(_iter_nodes_for_param(p))
  File "/home/deb1/.local/lib/python3.9/site-packages/jedi/inference/star_args.py", line 31, in _iter_nodes_for_param
    function_node = tree.search_ancestor(param_name.tree_name, 'funcdef', 'lambdef')
  File "/home/deb1/.local/lib/python3.9/site-packages/parso/tree.py", line 17, in search_ancestor
    n = node.parent
AttributeError: 'NoneType' object has no attribute 'parent'
In [1]: from fastapi import P
```

**Comment by davidhalter** [comment]
I still think that this is the right fix, but I would like to have a test case for it :/. Did you intentionally remove it? I feel like this patch is still needed.

**Pull request closed without merging**
