### PR TITLE
Pull request for #563 : Mentioned atom in README.rst with links to extensions supporting jedi.

### PR DESCRIPTION
**Pull request by v3ss0n**

### CODE REVIEW

**Comment by davidhalter** [comment]
Awesome! But please also update the docs. It should be reflected in both of them.

**Comment by v3ss0n** [comment]
Updated in the docs. Also made pull request at auto-complete-plus-jedi to link back here too.

**Comment by davidhalter** [comment]
@v3ss0n I don't see the changes, probably you forgot to push!

Also could you try to squash the changes? I usually don't care too much, but these commits are really a bit too much :)

**Comment by v3ss0n** [comment]
Hey
Yeah  ah ok , i will check.

**Comment by davidhalter** [comment]
Fixed by #602. If you want to modify something, you can still do that, but you need to do it with the current code base. I'm closing.

**Comment by v3ss0n** [comment]
Thanks a lot , it was really messy thing i did , confusing between markdown and rst. LOL

**Pull request closed without merging**
