### PR TITLE
[parser] add egg links to syspath

### PR DESCRIPTION
**Pull request by blueyed**
Followup to #532 (against the parser branch).

### CODE REVIEW

**Comment by davidhalter** [comment]
Great job!! Thanks so much. I will probably check a few things, but expect it to be merged soon.

**Comment by MiguelLatorre** [comment]
This line doesn't close the *opened* file descriptor.
> sys_path.insert(0, open(egg_link).readline().rstrip())

I guess this is better:
<pre>
with open(egg_link) as fd:
   line = fd.readline().rstrip()
sys_path.insert(0, line)
</pre>

**Comment by blueyed** [comment]
@MiguelLatorre 
Thanks, I've amended the commit and squashed the two previous commits while at it.

I've opted out of using the extra `line` var though:

                 # Add all egg-links from the virtualenv.
                 for egg_link in glob.glob(os.path.join(p, '*.egg-link')):
        -            sys_path.insert(0, open(egg_link).readline().rstrip())
        +            with open(egg_link) as fd:
        +                sys_path.insert(0, fd.readline().rstrip())

**Comment by davidhalter** [comment]
Thanks so much, took me a while to merge, but it looks good!

**Comment by davidhalter** [comment]
Merged. Therefore closing. Parser branch will not continue to exist.

**Comment by blueyed** [comment]
Cool.  Thanks for merging it!

**Pull request closed without merging**
