### PR TITLE
fix exception throwing when dealing with numpy

### PR DESCRIPTION
**Pull request by 21paradox**
Add Null check, Just passthrough empty result instread of throwing errors
This would fix https://github.com/davidhalter/jedi/issues/372 
Tested in smartos.

### CODE REVIEW

**Comment by davidhalter** [comment]
Why would scopes be None? And why would self.scope not have a names_dicts attribute? These are the really important questions here.

**Comment by 21paradox** [comment]
self.scope doesn't have names_dicts attr maybe because of c extensions.
I'm not 100% sure.
I just have tested one module  and numpy, they both not 100% written in python

**Comment by davidhalter** [comment]
You have to get behind the reason why this would happen. I'm not going to merge assumptions.

**Comment by 21paradox** [comment]
Very sorry for that pr. I will take a deep looking at the problem.

**Pull request closed without merging**
