### PR TITLE
Add BaseName.definition_[start,end]_position

### PR DESCRIPTION
**Pull request by pappasam**
Provides two public (property) methods getting the (row, column) of the start / end of the definition range. Rows start with 1, columns start with 0.

Resolves https://github.com/davidhalter/jedi/issues/1576

Note: I cannot run tests locally so, unfortunately, I didn't write any. See comment in issue mentioned above.

### CODE REVIEW

**Comment by pappasam** [comment]
I’ll write tests soon, please don’t merge until then!

**Comment by pappasam** [comment]
@davidhalter I've added the tests!

**Comment by davidhalter** [comment]
Thanks again!

I ended up changing a few things that I didn't notice and wanted you to know:

- I'm not using properties anymore. For most things in APIs properties are a bad idea, because you cannot modify their behavior with params anymore. 2d17b813138f400ef948d42cb411563af34077c2
- Used parametrize for tests, I like that better for tests in Python fa6194c0a9c5907e2c8fe046009d3aea2b9d53a4
- There was an AttributeError for some cases (and the return value can be None -> so it's an Optional). 8fdf16b316aedf6f581ef97ac9d63c843cf25898

**Comment by pappasam** [comment]
@davidhalter ah, gotcha, glad you caught those!

That said, the change in 8fdf16b may introduce a bug. The way I read it, if `self._name.tree_name` is None, the line `definition = self._name.tree_name.get_definition()` would raise a missing attribute exception, no?

We'd probably want the check to go:

```python
if self._name.tree_name is None:
    return None
definition = self._name.tree_name.get_definition()
if definition is None:
    return self._name.tree_name.end_pos
```

Also, we'd probably also want to do this exact same check for `get_definition_start_position`, right?

**Comment by davidhalter** [comment]
Very good point. I think we finally arrived at a good solution :).

**Pull request merged**
