### PR TITLE
Return 'class' as _PseudoTreeNameClass.type (fix #1578)

### LINKED ISSUE #1578: `_pseudotreenameclass` as `BaseName` type
```python
Python 3.7.4 (default, Sep 28 2019, 16:39:19) 
>>> from jedi import Script
>>> Script('from typing import Any\n').get_names()[0].type
'_pseudotreenameclass'
```

Please consider adding `_pseudotreenameclass` to the valid values list for [`BaseName.type`](https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.BaseName.type) or maybe return `class` instead.

Thanks!

### PR DESCRIPTION
**Pull request by muffinmad**
See #1578 for details.

### CODE REVIEW

**Comment by davidhalter** [comment]
Thanks a lot! Can you fix the failing test? (This is just a result of your improvement)

**Comment by muffinmad** [comment]
Please check if test case is correct.

Do I need to do something with decreased coverage?

**Comment by davidhalter** [comment]
No. I will deal with that myself, that's a different issue.

**Comment by davidhalter** [comment]
Thanks for your contribution!

**Pull request merged**
