### PR TITLE
Revert "Return SameEnvironment as a default, fixes #1226, #1196"

### PR DESCRIPTION
**Pull request by kashewnuts**
This reverts commit f9cbc65f2d114d6252a1b42f9deb958d54ab7b95.

refs: #1266

### CODE REVIEW

**Comment by davidhalter** [comment]
Python 3.3 is no longer supported. Python 3.3 has dropped security support now for more than a year. Just upgrade.

**Comment by kashewnuts** [comment]
It's a pity that the content of this PR is not being seen correctly.
I just **dropped** support for Python 3.3. https://github.com/davidhalter/jedi/pull/1267/commits/8648ca5925da9d617ee672149d76cef302c1cfb://github.com/davidhalter/jedi/pull/1267/commits/8648ca5925da9d617ee672149d76cef302c1cfbf
It's better to delete from jedi since Python 3.3 support is left.

**Comment by davidhalter** [comment]
Ouch. Sorry! Can you please upload the branch again? It was definitely my fault. My brain was confused by the name "revert". Happy to merge if you create the branch again. I will definitely merge the removal of 3.3.

However I disagree with the revert. We have discussed this extensively in some PRs.

**Comment by kashewnuts** [comment]
Thank you for reply!
I'd like to issue another PR to drop Python 3.3 support.
Because the problem that I wanted to solve seems to be discussed at https://github.com/davidhalter/jedi-vim/issues/870.

**Pull request closed without merging**
