### PR TITLE
third-party: use python/typeshed

### PR DESCRIPTION
**Pull request by blueyed**
I could not find a specific reason to use a fork here, since there
appear to be no changes.

Also updates it to the current version, fixing/improving many things.

### CODE REVIEW

**Comment by davidhalter** [comment]
There are definitely changes, it's just that we should probably update from time to time.

**Comment by blueyed** [comment]
Changes in your repo?
(Github just said that it was behind master?!)

**Comment by davidhalter** [comment]
There is a `jedi` branch :)

**Comment by blueyed** [comment]
I see.. :)
There are conflicts, so I think it is better for you to update it.

**Comment by blueyed** [comment]
btw: you could change the default branch in your fork.

**Comment by davidhalter** [comment]
I updated the default branch. :)

**Pull request closed without merging**
